#ifndef GAME_ENGINE_H
#define GAME_ENGINE_H

/* The main module's game code (src/engine): the functions other modules call, declared as they are defined. */

#include "nitro/types.h"
#include "nitro/fx/fx.h"
#include "game/actor.h"
#include "game/ai_task.h"

void AccumulateVec3Scaled(int *a, int *b, int scale, int flag);
void Actor_ArmWithMessage(void *obj, int a, int b, void *c, int d);
int Actor_InitEntityLink(char *pSelf, int record);
int Actor_ResolveGround(VecFx32 *pos, int *self, int *pOut);
void Actor_SetBindingByte(char *p, int i, char v);
void Actor_SetVecAndSyncChild(void *pPtr, const VecFx32 *src);
int Actor_StartMotion(void *obj, int p2, int p3, int p4);
int AllocFromExpHeapWrapper(int size, int *heap);
int Angle_TurnToward(int currentAngle, int targetAngle, int maxStep, int *outAngle);
void AnimObj_BindTrackAtLastFrame(void *self, unsigned short idx, short blend, unsigned char value);
void AnimStream_Advance(int obj, int delta);
int Anim_GetBlendFactor(int param_1, unsigned int param_2, int param_3);
int Anim_GetChannelState(unsigned short *r0, int r1);
int Anim_GetFrame(char *pR0, int r1);
int Anim_GetLengthQ12(char *pR0, int r1);
fx32 Anim_InterpEased(fx32 t, fx32 p0, fx32 p1, fx32 p2);
void AnmPlayer_SetFrameStep(int *p, int v);
int Archive_FindNameIndex(int desc, const char *name);
int Archive_GetMember(void *pR0, int r1, int r2);
unsigned int Archive_SubfileIsCompressed(unsigned int param_1);
int ArrayEntryPtrD0(int index);
void Bg_SetMainBg0Control(int size, int colorMode, int screenBase, int charBase);
void Bg_SetMainBg1Control(int size, int colorMode, int screenBase, int charBase);
void Bg_SetMainBg2AffineControl(int arg0, int arg1, int arg2);
void Bg_SetMainBg2ExtControl(int arg0, int arg1, int arg2);
void Bg_SetMainBg2TextControl(int arg0, int arg1, int arg2, int arg3);
void Bg_SetMainBg3AffineControl(int arg0, int arg1, int arg2);
void Bg_SetMainBg3ExtControl(int arg0, int arg1, int arg2);
void Bg_SetMainBg3TextControl(int arg0, int arg1, int arg2, int arg3);
void Bg_SetSubBg0Control(int size, int colorMode, int screenBase, int charBase);
void Bg_SetSubBg1Control(int size, int colorMode, int screenBase, int charBase);
void Bg_SetSubBg2AffineControl(int arg0, int arg1, int arg2);
void Bg_SetSubBg2ExtControl(int arg0, int arg1, int arg2);
void Bg_SetSubBg2TextControl(int arg0, int arg1, int arg2, int arg3);
void Bg_SetSubBg3AffineControl(int arg0, int arg1, int arg2);
void Bg_SetSubBg3ExtControl(int arg0, int arg1, int arg2);
void Bg_SetSubBg3TextControl(int arg0, int arg1, int arg2, int arg3);
void Bg_WriteMainBg0Cnt(int size, int colorMode, int screenBase, int charBase, int extPal);
void Bg_WriteMainBg1Cnt(int size, int colorMode, int screenBase, int charBase, int extPal);
void Bg_WriteSubBg0Cnt(int size, int colorMode, int screenBase, int charBase, int extPal);
void Bg_WriteSubBg1Cnt(int size, int colorMode, int screenBase, int charBase, int extPal);
void BitArray_ClearBit(int *bits, int n);
u32 BitArray_GetField(u32 *base, u32 bitOffset, u32 bitCount);
void BitArray_SetField(u32 *base, u32 bitOffset, u32 bitCount, int value);
int BitArray_TestBit(void *pBits, int n);
void Boot_InitVBlank(void);
void Bounds_FromCenterRadius(int *p);
unsigned int BuildSlotMask(int param_1, int param_2);
int ByteCode_ResolveOperand(void *pArg1, char *pArg2);
void CallVirtSlot0(int *ptr, int arg1, int arg2, int arg3, int arg4);
int CallVirtSlot1(int *p, int q);
void Callbacks_ClearByteAndRun2(void);
int Callbacks_Init(void);
void Callbacks_Run(int index);
void Callbacks_RunTableEntry(int index, int arg1, int arg2, int arg3);
void Callbacks_RunTableEntryB(int index, int arg1, int arg2, int arg3);
void Callbacks_RunTableEntryC(int index, int arg1, int arg2, int arg3);
void CamAnim_EvalDelta(char *a, char *b, void *c);
void CamAnim_FreePlayer(void *ptr);
int CamAnim_IsActive(int *p);
void CamAnim_Release(void **p);
void CamAnim_ResetProjection(int *ptr);
int CamAnim_SelectAnim(void **p, int idx);
int CamAnim_Start(int *this_, int seq);
void Camera_Init(int *param_1, unsigned int param_2, unsigned int param_3, unsigned int param_4);
void ChannelBuf_Append(const void *src, unsigned int size, int channel, int reset_flag);
void ClampAndStoreLevelEntry(int a, int b, int v);
void ClampToLimitsWithPenalty(VecFx32 *pos, unsigned char *bounds, fx32 *penalty);
void ClampToRange0to16At0x4628(int p, int v);
int ClearFlag20InitChildAndSyncTransform(int this_, int arg1, int arg2, int arg3);
int ClearFlag20InitChildAndSyncTransform2(int this_, int arg1, int arg2, int arg3);
void ClearFlag8HandleIfNot10(int this_);
void ClearGlobalFields80to84(void);
void ClearGlobalPtrE8AndHead(void);
void ClearListAndDestroy(int this_);
void ClearNodeIfHeadMatches(int p);
void CloseDebugOverlay(void);
void Cmd_DispatchWithFlag(int index, unsigned short *args, int arg1, int arg2);
int CollModel_GetEntryField14(void *model, void *key);
int Coll_ComputeSphereRayOffset(const VecFx32 *a, const VecFx32 *b, const VecFx32 *c, fx32 d, void *e);
void Collider_InitCylinderContact(char *a, char *b, char *c);
int Collider_InitPlaneY(int *r0, int r1, short *r2);
void Collider_InitSphereContact(char *p1, char *p2, char *p3);
int Collision_ProbeGround(void *cont, void *key, void *out);
int CommitCachedByteIfChanged(void *arg, int arg1);
int CommitRecordCursor(int param_1, int *param_2);
unsigned int ComputeAlignedEndOffset(int param_1, int *param_2);
int ConstReturn0(void);
int ConstReturn0_2(void);
int ConstReturn1(void);
int ConstReturn1_2(void);
int ContextEntry_InitForRootHeap(void);
void CopyToSlotTable8(void *dst, int idx);
unsigned int CountBlocksForSpan(unsigned int param_1, int param_2);
void DList_InsertAfter(int **r0, int **r1, int **r2);
void DList_Unlink(int **head, int *node);
void DList_UnlinkAndClear(int *head, int *node);
int DeferredAction_Gate(int param_1, unsigned int param_2);
int DeferredDraw_Release(int param_1, int param_2, int param_3, int param_4);
void DestroyInstance(void *pArg1);
void DestroyListNode(int this_, int node);
void DestroySubObjectsAndCleanup(int this_);
void DestroySubObjectsAndCleanup2(int this_);
unsigned int DetachThenApplyNode(int param_1, unsigned int *param_2, int param_3);
int DispObjList_AddResource(void *pList, void *b);
int DispObjList_GetEngine(int list);
void DispObjList_Update(int base, int arg);
int DispObjList_UpdateImmediate(int list);
int DispObjList_UpdateQueued(int list);
int DispatchByNodeKind(void *pPtr);
void DispatchByPartType(int param_1, unsigned short *param_2, int param_3, int *param_4, int param_5, int param_6);
void DispatchObjectCallbacks(void *pThis_, int arg1);
void DispatchThreeOptionalOpsB(int param_1, int param_2, int param_3, int *param_4);
int DispatchTrackEntryIfReady(int param_1, unsigned int param_2);
void DispatchWithReentrantScratch(int param_1, int param_2, int param_3, int param_4);
void DrawTileIfReady(int param_1);
void Draw_ScaledValue(void *pSelf, unsigned int param_2, int param_3, int param_4, int param_5);
void EffectList_Step(void);
int EffectList_StepIfIdle(void);
int EnqueueGfxCmd0(int arg0, int arg1, int arg2);
int EnqueueGfxCmd1(int arg0, int arg1, int arg2);
void EnsureServiceInstance(void);
int EntityManager_ReleaseViews(void);
int EntityManager_ResetSingleton(void);
void EntityMgr_AllocRecords(int n);
void EntityMgr_AttachTrackData(unsigned int nTrack, const char *pName, const void *src, unsigned int size);
void EntityMgr_DropTextureImage(int index);
int EntityMgr_GetModelGroupCount(void);
int EntityMgr_GetVramStateDepth(void);
void EntityMgr_LinkChild(int param_1, int param_2, int param_3);
void EntityMgr_PopVramState(void);
void EntityMgr_PushToList(int list, int *node);
unsigned char EntityMgr_PushVramState(void);
void EntityMgr_SetTransition(int param_1, int param_2, int param_3);
void EntityMgr_SpliceIntoListA(int index, void *node, void **anchor);
void EntityMgr_SpliceIntoListB(int index, void *node, void **anchor);
void EntityMgr_UnlinkFromListA(void *node);
void EntityMgr_UnlinkFromListB(void *node);
void EntityMgr_UnlinkFromListC(void *node);
int EntityRecord_DropTextureImage(int record);
void Entity_Activate(unsigned char *ptr, int nList);
int Entity_AttachNode(int entity, int *node);
void Entity_Deactivate(unsigned char *ptr);
int Entity_DetachNode(int entity, int *node);
void Entity_ForwardToSlot(int param_1, int param_2, int param_3, void *pArg4, int param_5);
int Entity_LoadAndAttach(int index, int p2);
int Entity_Register(void *obj, void *pP2, int p3, int p4);
void Entity_SubmitRenderNode(int param_1, int param_2, int param_3, int param_4);
void Entity_Tick(int index);
int EventRecord_Init(unsigned int *param_1, unsigned int *param_2, unsigned int param_3, int param_4);
int ExpHeap_Free(int block, int *heap);
int ExpHeap_ResizeBlock(int *heap, void *memoryBlock, int size);
void FSi_BindCardTransfer(unsigned int id);
void FileLoader_FreeRequest(int *request);
BOOL FileLoader_Init(void);
int FileLoader_LoadInto(const void *data, void *buffer, int maxSize);
int FileLoader_LoadSync(const void *data, void *buffer, int size);
void FileLoader_ThreadMain(void *arg);
int FindResourceIndexByName(void *a0, void *a1);
int FontResource_Destroy(void *p);
int Font_LoadUTF16(int *font, char *name, int arg2, int arg3);
void ForEachChildDispatch(int this_, int arg1);
void ForwardQuery64Result(void);
void ForwardToHandlerOrCurrentObject(int obj, int index, int fadeFrame);
int ForwardWithFlag1(int arg0, int arg1);
void FreeAllResourceTables(char *pP);
void FreeAndClearIfNonNeg(int *arg0, int arg1);
void FreeFieldAt8(char *pP);
void FreeInstanceMemory(void *p);
int FreeNodeAndChildLists(int *param_1);
void Fx64_FormatText(s64 value, int precision, char *pIntText, char *pFracText);
void Fx64_FormatWide(s64 value, int precision, u16 *pIntOut, u16 *pFracOut);
int Fx_Acos(int x);
s32 Fx_Tween(s32 start, s32 end, u32 elapsed, u32 duration, u32 curve);
BOOL G3dRes_DefaultSetup(void *pResData);
void G3d_ResetGlobalState(void);
void GameConfig_Load(int param_1, int param_2);
void GameSession_SetSyncEnabled(int enable);
void GameState_ClearFlag(int flag);
int GameState_GetField(int arg0, int arg1);
int GameState_IsFlagSet(unsigned int arg);
void GameState_SetField(unsigned int arg0, unsigned int arg1, unsigned int arg2);
int GameState_SetFlag(int arg0);
int Game_ActionAssign(void *st, short *operand);
int Game_ActionEnqueueCmdIfChanged(int param_1, u16 *param_2);
int Game_ActionInitObject(int *param_1, short *param_2);
int Game_ActionLoadArenaResource(int *param_1, short *param_2);
int Game_ActionReturn4(void);
int Game_ActionSetBranchTarget(int param_1, int *param_2);
int Game_ActionSetupNamedCall(int param_1, u16 *param_2);
int Game_ActionTurnHandler(int param_1, int param_2);
void Game_ApplyModeFlags(void);
void Game_EnterPauseScene(void);
int Game_PollSceneAlive(void);
void Game_PushObjectSlot(int *param_1, int *param_2, int param_3, unsigned *param_4);
int Game_RunActionScript(char *st);
void Game_RunSceneLoop(void);
void Game_UnwindActionStack(char *st);
void Game_UpdateObjectMotion(char *obj);
int GetBGScreenBaseForLayer(int index);
int GetEntryField20ByIndex(int idx);
int GetField4UnlessState2(int arg0);
int GetFrameRateMode(void);
unsigned short GetGlobalU16At4(void);
unsigned short GetGlobalU16At6(void);
int GetLanguage(void);
int GetMasterBrightnessMain(void);
int GetMasterBrightnessSub(void);
int GetPlayerSlotTableEntry(int idx);
int GetWordAt0x58c(int p);
void Gfd_LoadTexB(void *src, unsigned offset, unsigned size);
void Gfd_LoadTexPlttB(void *src, unsigned offset, unsigned size);
int Gfx_BgLayerCommand(unsigned int x);
void Gfx_DispatchByPairKeyA(int index, unsigned short *args, int arg1, int arg2);
void Gfx_DispatchByPairKeyB(int index, unsigned short *args, int arg1, int arg2);
int Gfx_EnqueueBgUpload(int arg0, int arg1, int arg2);
int Gfx_EnqueueSurface(int param_1);
int Gfx_EnqueueTableCmdAt14(int idx, void *p, int arg2, int arg3);
int Gfx_EnqueueTableCmdAtC(int idx, void *p, int arg2, int arg3);
int Gfx_GetBgUploadTarget(int index);
void Gfx_Reset2DEngines(void);
int Gfx_ResetDisplayAndVram(int *self, int arg);
void Gfx_RestoreAfterPause(void);
void Gfx_SetupSubEngine(void);
int Gfx_ToggleCaptureMode(void *ptr);
void Gfx_UploadBlock(unsigned char *ptr);
int Header_InitWithLimits(short *o, short *src);
int Heap_GetCurrent(void);
int Heap_SetCurrent(int heap);
void InitContextEntryOnce(int param_1);
int InitNodeAndStoreParams(int this_, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6);
int InitNodeAndStoreParamsMode1(int this_, int arg1, int arg2, int arg3, int arg4);
int InitNodeAndStoreParamsMode2(int this_, int arg1, int arg2, int arg3, int arg4);
int InputState_Init(void);
void Input_DebounceSlot(int index);
void InstallHandlerPairByFlag(int arg0);
int Instance_ReleaseIfDead(int *p);
void InvokeSubObjectMethod(int this_, int arg1);
void InvokeSubStructAndStampByte(int arg0, int arg1);
int IsDerefZero(int arg0, int *arg1);
int IsField1cEqualData42910(int arg0);
int IsField1cEqualData42940(int arg0);
int IsKind1Or4(int param_1);
int IsSubStructValidAndReady(void);
int KeyRepeat_Step(void *p);
void LatchPendingRequestOnce(void);
void LinkChildNode(int *param_1, int *param_2, unsigned int *param_3);
void ListPushFront(int *head, int *node);
unsigned int List_InsertSorted(void *pList, int extra, unsigned int key);
int List_Next(void *pR0);
int List_TryInvokeEntry(int param_1);
int Load2DArrayU8(int arg0, int arg1);
int Load2DArrayU8_2(int arg0, int arg1);
void LoadActorOverlay(void);
int LoadArrayInt244(int index);
int LoadArrayU16Stride14At0c(int index);
int LoadArrayU8At0cc(int index);
int LoadArrayU8At0ce(int index);
int LoadGlobalIntAtC(void);
int LoadGlobalPtr4FieldDcOrZero(void);
int LoadGlobalPtrField70(void);
int LoadGlobalS8At0(void);
int LoadGlobalU16At0(void);
void LoadOverlaySync(int a, int b);
int Loader_LoadOverlayImage(int a);
int Loader_LoadOverlayInfo(void *info, int proc, int id);
void Loader_PostIdRequest(unsigned short id, int arg1, int arg2);
void Loader_PostTypedRequest(unsigned short id0, unsigned short id1, int arg2, int arg3);
int Loader_SleepIfBusy(void);
void Loader_WaitAndReleaseSlot(int param_1, int param_2, int param_3, int param_4);
int LookupPairKey(short *table, int key1, int key2);
void MainBlob_ResetSlotRows(void *pArg1, void *pArg2);
unsigned short Mem_ReadU16(unsigned short *p);
unsigned char MobiClip_GetStreamStepDelta(int ****p);
void MobiClip_ResolveGlyphRecord(int *ptr, int *out, unsigned int value);
void ModelArchive_DropTextureImage(int archive, int heap, int arg3);
int ModelFile_LoadFirst(const char *path);
void ModelNode_Destroy(char *arg0);
void ModelNode_UpdateTree(char *node, int arg);
int Model_DropTextureImage(int model);
void Mover_StepActor(int *ptr, int arg);
int MsgArchive_FindEntryByName(unsigned char *arg0, void *arg1);
int MsgDb_AllocRecord(int *rec_out, unsigned int size, short kind, int keep);
int MsgDb_BuildEntryRecord(int *rec_out, int index, int keep, int db);
int MsgDb_DecodeDb13(int *rec_out, int index, int keep);
int MsgDb_DecodeDb14(int *rec_out, int index, int keep);
int MsgDb_DecodeDb16(int *rec_out, int value, int keep);
int MsgDb_DecodeDb19(int *rec_out, int index, int keep);
int MsgDb_DecodeDb1A(int *rec_out, int index, int keep);
int MsgDb_DecodeDb1C(int *rec_out, unsigned int index, int keep);
int MsgDb_DecodeDb1D(int *rec_out, int index, int keep);
int MsgDb_DecodeDb1E(int *rec_out, int index, int keep);
int MsgDb_DecodeDb1F(int *rec_out, int index, int keep);
int MsgDb_DecodeDb20(int *rec_out, int index, int keep);
int MsgDb_DecodeGenericRecord(int *param_1, int param_2, unsigned int param_3, int param_4);
int MsgDb_FetchEntryPair0x1b(int *rec_out, int index, int keep);
int MsgDb_FetchRecord(void *pRec_out, int db, unsigned int index, int keep);
void MsgDb_InitTable(void);
int MsgDb_IsLoaded(int param_1);
int MsgDb_LoadDb(int id, int mode);
int MsgQueue_Contains(unsigned int id);
int MsgQueue_Enqueue(int param1, int param2, unsigned short *param3);
int MsgQueue_GetHeap(void);
void MsgQueue_Init(void);
void MsgQueue_MarkSlotReceived(unsigned int handle, unsigned int playerIndex, unsigned int bit);
unsigned short MsgQueue_Post(int nKind, const void *pCmd, unsigned short nSize);
void MsgQueue_RecvDispatch(unsigned char *param_1, int param_2);
void MsgQueue_ResendForPeer(int param_1);
int MsgQueue_SendGate(int param_1, void *pArg2, unsigned short param_3);
void MsgQueue_SetMoviePlaying(int playing);
void Mtx33_ApplyFixedRotation(void *ptr);
int NitroFile_GetSection0Byte9(unsigned char *obj);
void Node_CallHook80(char *p);
void Node_ComposeWorldSrt(int *ptr);
int Node_FlipDoubleBuffer(int p);
void Node_SetPosAndNotify(unsigned char *ptr, const VecFx32 *src);
void Node_SetRotationFromMtx(unsigned char *ptr, int arg1);
void Node_UnlinkAndClearRefs(int *node);
void OamBuffer_Flush(char *self, int flag);
int Oam_GetObjHeight(int *p);
int Oam_GetObjWidth(int *p);
int ObjNode_InitFromDesc(char *obj, int *desc);
void Obj_AdvanceGauges(int *self, int elapsed);
void Obj_CommitAllSlots(char *arg0);
void Obj_CommitAlphaBlend(void *pBase, int idx);
int Obj_Destroy(int *param_1);
int Obj_ForwardInnerPayload(void *pPtr, int arg1, int arg2, int arg3, unsigned short arg4);
void Obj_ForwardToSub1c(unsigned char *pPtr, int arg1, int arg2, int arg3, int arg4, int arg5);
int Obj_GetCellScaledField(int *obj, int idx, int idx2);
int Obj_GetCurrent(void);
int Obj_GetFrameCount(void);
int Obj_GetIndirectWord(int *r0, int r1);
int Obj_GetSub2c(int r0);
int Obj_GetWord18(char *pP);
int Obj_GetWord28(int *p);
int Obj_GetWordC(int *p);
void Obj_InitChannelsAndRun(char *pArg1);
void Obj_InitSystem(void);
void Obj_InvokeInnerVtable4(unsigned char *pPtr);
void Obj_InvokeInnerVtable8(unsigned char *pPtr, int arg1, int arg2, int arg3, int arg4);
int Obj_IsIdFree(int param_1);
void Obj_LinkNode(int node);
int Obj_LoadResourceNode(void *a, void *b);
int Obj_MarkIfSubObjectReady(unsigned char *o);
void Obj_PrepAltTransform(int param_1);
int Obj_Release(void *object);
void Obj_RelocateSections(int *param_1, int param_2);
int Obj_ResetBothSubBlocksAndArm(char *o);
int Obj_ResetSize30(int *p);
void Obj_SetField14(int *p, int v);
void Obj_SetFlagBit3(void *pP, int flag);
void Obj_SetFourWords(int *p, int a, int b, int c, int d);
void Obj_SetIndirectWord(int **p, int v);
void Obj_SetTransition(u8 *pObj, int bEnable, int nDuration);
void Obj_SetWord4(int *p, int v);
void Obj_SetWord54(int *p, int v);
void Obj_SetWord8(int *p, int v);
void Obj_StepMotionTransform(int *param_1, int *param_2, int *param_3, int *param_4, int *param_5);
void Obj_UnlinkNode(int param_1);
void Obj_UpdateAll(int paused);
void Overlay105_Load(void);
void Overlay105_Release(void);
int P2_ExtractString(unsigned short **out_ptr, unsigned int *out_count, int db, int k, int keep);
void PackDisplayReg0x400000c(int size, int colorMode, int screenBase, int charBase);
void PackDisplayReg0x400000e(int size, int colorMode, int screenBase, int charBase);
void PackDisplayReg0x400100c(int size, int colorMode, int screenBase, int charBase);
void PackDisplayReg0x400100e(int size, int colorMode, int screenBase, int charBase);
int Pad_Sample(void);
void Params_BuildIndex(void);
int ParseSlotQuantityId(void *world, char *name);
void PartyMember_AddEntryPair(int member, unsigned short *pair);
void PartyMember_ClearEntryPairs(int member);
void PartyMember_ClearLists(int slot);
void PartyMember_RebuildDerived(int member, int a, int cls, int b);
void PartyMember_RefreshDialogue(int slot, int msgArg);
void PartyMember_Reset(int slot, int kind, int level);
void PartyMember_ResetWithKind(int slot, u8 kind, int a, int b);
void PartyState_AllocRecord(void);
void PartyState_ClearHeldItem(void);
void PartyState_CopyEquipTables(int a, int b);
void PartyState_FreeRecord(void);
int PartyState_IsHoldingItem(int item);
void PartyState_ReleaseNodes(void);
void PartyState_Reset(void);
void PartyState_ResetBuffers(void);
void PartyState_SaveTables(void);
void PartyState_SetHeldItem(short item, int held);
void PauseMenu_ConfirmFrame(void);
void PauseMenu_Frame(void);
int PauseMenu_GetMode(void);
void PauseMenu_Open(void);
void PauseMenu_OpenIfAllowed(void);
int PauseMenu_PollInput(void);
void PauseMenu_SetAllowed(char allowed);
void PauseMenu_SetMode(int mode);
void Pause_LoadResources(void);
int PickCloserAlongEdge(int *param_1, int *param_2, int *param_3, int *param_4);
int PlaySound(int arg0, int arg1);
void PlaySoundChecked(void *ptr, int arg);
void PollAndLatchRequest(void);
void PrintfDestWide_FillChar(unsigned int *buf, unsigned short val, unsigned int count);
int PrintfDestWide_PutChar(int *arg0, short arg1);
void PrintfDestWide_PutString(unsigned int *buf, unsigned short *src, unsigned int count);
void PrintfDest_FillChar(unsigned int *buf, unsigned char val, unsigned int count);
int PrintfDest_PutChar(int *arg0, char arg1);
void PrintfDest_PutString(unsigned int *buf, char *src, unsigned int count);
void ProcessListChildren(int this_);
void Projection_LoadDefaults(void *pP);
void PublishArchiveVTableAndSeedRng(void);
void QuadTree_InsertObject(int *param_1, int param_2);
void QuadTree_RemoveObject(int *param_1, int param_2);
void QuatFromAxisAngle(void *pOut, void *pAxis, int angle);
void Quat_Add(int *out, int *a, int *b);
void Quat_FromMtx33(s32 *dst, s32 m[3][3]);
int Quat_Length(int *v);
int QueryActiveStateOrDelegate(void);
int QueryAndRegisterNode(int obj, unsigned short *keys, int arg3, int arg4);
unsigned int Rand16NextScaled(unsigned int range);
int RandNext(void);
unsigned int RandNextScaled(unsigned int range);
int RecentRing_Record(unsigned short id, unsigned char kind);
void Record_EnsureAllocatedAndSetId(int n);
int Record_Init(void *p, int field22_short, int field28);
int Record_ReleaseSlot(int *slot);
void RefreshObjectCallbacks(void *pPtr, int arg);
int RegisterActorOrRetry(void *obj, int arg1);
void RegisterNamedTask(int a, int b, int c, int d);
void RegisterSeqAndInit(void *pThis_, void *pArg1, int arg2, int arg3);
void RegisterSeqAndInitField74(int this_, int arg1, int arg2, int arg3);
int RegisterSubscriberSlot(void *pArg1, void *pArg2);
void ReleaseField74AndCleanup(void *pThis_);
void ReleaseNodeResources(void *pArg1);
void ReleaseServiceInstance(void);
int RemoveChildFromListByPtr(int param_1, int *param_2, unsigned int param_3);
void RenderList_PushEarly(int index, void *node);
void RenderList_PushMain(int index, void *node);
void Render_ApplyFactorToViews(unsigned int mask, fx32 scale);
void Render_DrawViewLists(int index);
void Render_ReleaseItemOnce(int *param_1);
void Render_ReleaseNodeItem(unsigned char *param_1);
void Render_SubmitNode(void *obj, int index, int p3, void *p4);
void Req_SetPendingFields(int a, int b, int c);
void RequestQueue_SetOrPushKind3(int arg);
int ResSlot_Release_2(int param_1);
void Res_LoadSpriteSet(void *pArg1, void *pArg2, int param_3, int param_4, int param_5);
void Res_RequestIdPair(int n);
int Res_TearDownBlock(void);
int ResetRequestRecord(int req);
void Resource_BindByName(void *pHandle, void *pName);
int Resource_BindFileToSlot(unsigned int *pSlot, int nNode, unsigned int *pFile, int nHeap);
void RigWork_Update(char *self, int arg);
void Rng_Seed(int a, int b, int c);
void Save_StoreSlotTables(void);
int ScaleAroundPivot(int arg0, int arg1, int arg2);
void ScaleVec3Fixed27(int a, int *in, int *out);
void SceneNode_AttachToModelJoint(void *a0, void *a1, void *a2);
void SceneNode_Detach(int obj);
void SceneNode_Disable(void *pP);
void SceneNode_Enable(void *pP);
void SceneNode_SetFlag40(void *pP, int flag);
int Scene_AdvanceToPending(void);
int Scene_ClearPending(void);
void Scene_Leave(void);
void Scene_RequestPending(int arg0, int arg1);
int Scene_StepAndContinue(void);
int ScriptCmd_ArmPair(int param_1, int param_2);
int ScriptCmd_DispatchToHandler(void *arg0, void *cmd);
int ScriptCmd_ForwardThreeToHandler(int param_1, unsigned short *param_2);
int ScriptCmd_FreeSlotEntry(int param_1, int arg1);
int ScriptCmd_PlaySound(int param_1, unsigned short *param_2);
int ScriptCmd_QueueSoundKind1(void *arg0, int arg1);
int ScriptCmd_RequestKind3(void *vm, void *op);
int ScriptCmd_RequestResPair(void *p, char *buf);
int ScriptCmd_SetSelection(int param_1, int param_2);
int ScriptCmd_StartStream(int param_1, unsigned short *param_2);
int ScriptCmd_StoreDoubled(void *arg, int arg1);
void ScriptPool_FreeSlot(void *ptr);
void ScriptQueue_Push(unsigned char kind, unsigned char arg, unsigned short value);
int ScriptVm_ReadOperandFx32(void *st, void *cmd);
int ScriptVm_ReadOperandInt(void *arg, void *cmd);
int ScriptVm_ResolveActorIndex(int ctx, int index);
void ScriptVm_UpdateActiveCamera(int script);
int Script_Cmd_PlayEntityCutsceneCam(int ctx, char *args);
int Script_Cmd_PlayEntityCutsceneCamWait(int ctx, char *args);
int Script_StepAndIsIdle(void);
int Script_ValueToFx32(short *value);
int Session_CheckSceneLoop(void);
void Session_Destroy(void);
int Session_Exists(void);
int Session_GetLinkMode(void);
unsigned int Session_GetLocalPlayerIndex(void);
int Session_GetSetup(void);
int Session_IsActive(void);
int Session_IsReady(void);
int Session_IsSceneInterruptible(void);
void Session_LayoutPacketSlots(int mode);
u32 Session_PackConnectedPlayerMask(void);
int Session_RandNext(void);
unsigned Session_RandNextScaled(unsigned range);
void Session_SetMoviePlaying(int playing);
void Session_Shutdown(void);
void Session_StoreSetup(void *setup);
void SetGameMode(int arg0);
void SetGlobalShort2To1(void);
void SetMasterBrightnessMain(int brightness);
void SetMasterBrightnessSub(int brightness);
int SetSelectionIfChanged(int param_1);
void SetSubEngineGraphicsModeFromTable(int *table);
void SetSubitemState(void *self, unsigned short idx, short blend, unsigned char value);
void SetSubitemValueFromIndex(void *pArg1, int param_2, unsigned param_3);
void SetWordAt0x588To1(int p);
void Shutdown3DSubsystem(void);
int Sleep_Block(void);
int Sleep_IsAllowed(void);
int Sleep_Unblock(void);
void SlotNodeList_FreeAll(void *p);
int SlotTable_AddEntry(void *a0, int a1, int a2);
int SlotTable_FindFree(char *base);
int SlotTable_GetEntryFrame(char *arg0, int arg1);
void SlotTable_InitCellAnim(void *p, unsigned int a, void *q, int b);
void SlotTable_SetBlendAlpha(char *p, int alpha);
void SlotTable_SetEntryPair(char *base, int i, int va, int vb);
void SlotTable_SetEntryStyle(void *pArg1, int param_2, int param_3);
void SlotTable_SetEntryVelocity(void *pBase, int idx, int scale);
void SlotTable_SetMode(int *p, int v);
int Slot_AllEntriesFilled(int a);
int Slot_CalcRangeCap18(int a);
void Slot_ClearMatchingEntry(int a, short *key);
int Slot_EvalPackedParam(int a, int b);
int Slot_EvalPackedParamWith(int a, int b, int c);
void Slot_ForwardToEntry(void *pArg1, int param_2, int param_3);
int Slot_GetPositionPtr(int r0, int r1);
int Slot_IsVisible(int base, int index);
int Slot_SetFlagBit1(int r0, int r1);
void Slot_SetMode2Bit(unsigned char *pBase, int index, int value);
void Slot_SetVisible(unsigned char *pBase, int index, int value);
unsigned int Slot_Spawn(unsigned int param_1, unsigned int param_2, unsigned int *param_3, unsigned int param_4);
void Slot_UnlinkAll(void *p);
void Slot_UnlinkIfLinked(int *pPtr, int index);
int Snd_RegisterSeqAndBind(void *pA, void *pB, void *pC, int d);
BOOL SoundBank_Acquire(int id, int dataId);
BOOL SoundBank_Release(int id);
BOOL SoundCtx_Init(void);
void SoundMgr_ExpireRequests(void);
int SoundMgr_GetStreamNextPos(int index);
int SoundMgr_IsBgmFadingOut(void);
int SoundMgr_IsState1(void);
int SoundMgr_PauseBgm(int arg);
void SoundMgr_PopQueued(void);
void SoundMgr_PrepareStream(int param_1, int param_2);
int SoundMgr_QueueKind1(int arg);
void SoundMgr_QueueRequest(int kind, int arg1, int arg2);
void SoundMgr_SetListener(VecFx32 *src, VecFx32 *a, VecFx32 *b);
void SoundMgr_SetListenersEnabled(int enabled);
void SoundMgr_SetSeEnabled(char enabled);
int SoundMgr_StartStream(int arg0, int arg1);
void SoundMgr_StopAllSePlayers(void);
void SoundMgr_StopBgm(int arg);
int SoundMgr_SwitchBgm(int seq, int fade);
int SoundMgr_SwitchBgmResume(int seq, int fade);
void SoundMgr_Update(void);
void SoundMgr_WaitLoaderIfState1(void);
int SoundSeqHandle_IsActive(unsigned int handle);
void SoundSeqHandle_Stop(unsigned int arg);
int SoundStrm_HasPlaybackPos(int index);
void SoundSys_Start(const char *path);
void Sound_UpdateSpatial(int param_1);
void SpriteRes_Load(unsigned int param_1, char *param_2, int *param_3);
void Srt_SetRotationAxisAngle(void *param_1, int *arg1, int arg2);
void Srt_SetTranslationXYZ(void *pR0, int r1, int r2, int r3);
int StackAlloc_FreeIfSet(int a);
void StampByteAndInvokeSubStructAt(int arg0, int arg1);
void Store2DArrayU8(int arg0, int arg1, char arg2);
void StoreArrayInt244(int index, int value);
void StoreBytePairKeepMin(int param_1, int param_2, unsigned int param_3, unsigned char *param_4);
int StoreField74ThenForward(int arg0, int arg1, int arg2, int texSrc);
void StoreGlobalArrayEntry(int index, int value);
char StoreGlobalByteAt0(char arg0);
void StoreGlobalPtrArray4At0c(int index, int value);
void StoreGlobalShortAt0(short arg0);
void StoreToGlobalDblPtr(int arg0);
void StoreToGlobalIndexedIfSet(int index, int *arg1);
void StoreToGlobalPtr4Field28(int arg0);
void StoreToGlobalPtr4FieldDcIfSet(int arg0);
void StoreToGlobalPtr4FieldE4IfSet(int arg0);
void StoreU16FieldAndRefresh(unsigned int param_1);
void StoreValueInNamedEntry(int param_1, unsigned char *param_2, int *param_3);
int Stream_DecodeIntoStagingBuffer(char *o, int a, int c, int d);
void SubOam_SetupBitmapGrid(void);
void SubObject_DispatchDraw(int param_1, int param_2);
void SubObject_NudgeAndRedraw(int param_1, int param_2, int param_3);
void SubObject_SetDrawParams(unsigned char *ptr, int index, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7);
void SubObject_SetupDraws(void);
void SubObject_SetupDrawsForMode(void);
void SubResourceTable_Free(unsigned short *param_1);
void SubmitEntryIfActive(int arg0);
void TabPanel_HandleUpDown(int *pIndex);
void Table6_ResetAll(void);
int TableAppendRecord(int param_1, int *param_2);
void TailForwardTrackEntry(int param_1, void *pArg2, int param_3, int param_4);
void TailForwardTrackEntry_2(int param_1, int param_2, int param_3, int param_4);
int TaskList_FinishByTag(void *ptr, void *pValue);
void Task_MarkFinished(void *pP);
void TeardownNodeIfBit0Set(int this_, int arg1);
int Tex0_GetTexPlttParams(u32 *out, void *file, int setup);
void TextCanvas_DrawShadowedAt(char *ptr, int arg1, int arg2, int arg3, int arg4, int arg5);
int TextCanvas_ResolveColor(int r0, int *r1);
int TextWindow_GetTextWidth(int window, int text);
void Text_DrawDirectional(int self, int x, int y, int p4, unsigned int flags, int p6);
void Text_DrawDirectional_2(int self, int x, int y, int p4, unsigned int flags, int p6);
void Text_DrawWithShadow(void *pDctx, int x, int y, int depth, void *buf, int shadow);
void Text_FormatUtf16(int a, int b, int c, ...);
int TileSurface_Init4bpp(int a, int b);
int TileSurface_Init8bpp(int a, int b);
int TileSurface_InitAndUpload4bpp(void *pA, void *pB);
int TileSurface_InitAndUpload8bpp(void *pA, void *pB);
int TileTextRenderer_Destroy(void *pR0);
int Touch_StartAutoSampling(void);
void UnloadActorOverlay(void);
void UnloadOverlaySync(int a, int b);
int Utf8_ToUcs2(const void *pSrc, u16 *dst);
void VBlank_SetCount(int count);
void VBlank_UnregisterCallback(int unused, const char *name);
void Vec3ScaleAddQ27(fx32 s, const VecFx32 *a, const VecFx32 *b, VecFx32 *c);
void Vec3TransformViaTempMtx(void *in_vec, void *quat, void *out_vec);
int Vec4_DotFx12(int *a, int *b);
int Vec4_Normalize(void *pQ, void *pV);
void Vec4_ScaleFx12(unsigned int *out, int *v, int scalar);
void VecFx32FromVecS16(int r0, short *r1, int *r2);
void Widget_SetTagWord(unsigned short *p, unsigned short v);
int Word_ClearReturn1(int *p);
void Word_Set(int *p, int v);
int ZeroHalfThenFree(void *arg0);
void callIfTableEntrySet(int param_1, int param_2, int param_3);
void dispatchByObjTypeBits(int param_1, int param_2);
void initObjAndDispatch(int *p, int v);
void invokeObjCallbackGuarded(int param_1);
void invokeObjCallbackList(int param_1);
#ifdef SDK_BUILD_ARM
int main(void);
#endif
int queryTableEntry(int param_1, int param_2);
int remapIndexIfHwFlagSet(int param_1);
void setDualArrayEntry(int i, int v1, int v2);

#endif /* GAME_ENGINE_H */
